#!/usr/bin/env bash

set -e

ME=$(basename $0)
MYDIR=$(cd $(dirname $0)/.. && pwd)

###############################################################################
#
# Minimal checks
#
###############################################################################
[ -z "$1" ] && echo "$ME: missing directory" && exit 1
[ ! -d "$1" ] && echo "$ME: invalid directory" && exit 1

SRCDIR="$1"
shift

###############################################################################
#
# Compiler setup
#
###############################################################################
BUILDROOT=$MYDIR/build/root
CC=gcc
CFLAGS="-O3 -march=native"
CXX=g++
CXXFLAGS=$CFLAGS
CPATH=$BUILDROOT/include
LIBRARY_PATH=$BUILDROOT/lib
PKG_CONFIG_PATH=$LIBRARY_PATH/pkgconfig

CCACHE=$(which ccache || true)

if [ -n "$CCACHE" ]; then
    CC="$CCACHE $CC"
    CXX="$CCACHE $CXX"
fi

export CC CFLAGS CXX CXXFLAGS CPATH LIBRARY_PATH

###############################################################################
#
# Parallel compilation setup
#
###############################################################################
NPROC=$(which nproc || true)

[ -n "$NPROC" ] && NPROCS=$(nproc)

MAKEARGS=
CMAKEARGS=

if [ -n "$NPROCS" ]; then
    CMAKEARGS="--parallel $NPROCS"
    MAKEARGS="-j$NPROCS"
fi

###############################################################################
#
# Project build
#
###############################################################################
PROJECT=$(basename $SRCDIR)
BUILDDIR=$MYDIR/build/work/$PROJECT

rm -rf $BUILDDIR && mkdir -p $BUILDDIR

if [ -f $SRCDIR/CMakeLists.txt ]; then
    cmake \
        -DCMAKE_PREFIX_PATH=$BUILDROOT \
        -DCMAKE_INSTALL_PREFIX=$BUILDROOT \
        -DCMAKE_TOOLCHAIN_FILE=$MYDIR/toolchains/ext.cmake \
        -DBUILD_SHARED_LIBS=ON \
        -S $SRCDIR -B $BUILDDIR \
        "$@"
    cmake --build $BUILDDIR $CMAKEARGS
    cmake --install $BUILDDIR
elif [ -f $SRCDIR/meson.build ]; then
    cd $BUILDDIR
    meson \
        --prefix=$BUILDROOT \
        --pkg-config-path=$BUILDROOT \
        --cmake-prefix-path=$BUILDROOT \
        "$@" \
        . $SRCDIR
    meson install
elif [ -f $SRCDIR/autogen.sh ]; then
    (cd $SRCDIR && autoreconf -fvi)
    cd $BUILDDIR
    $SRCDIR/configure \
        --prefix=$BUILDROOT \
        --enable-shared
    make $MAKEARGS
    make install
elif [ -x $SRCDIR/config ]; then
    cd $BUILDDIR
    $SRCDIR/config --prefix=$BUILDROOT
    make $MAKEARGS
    make install
elif [ -f $SRCDIR/Makefile ]; then
    cd $SRCDIR
    make $MAKEARGS
    make prefix=$BUILDROOT install
else
    echo "$ME: don't know how to build $SRCDIR"
    exit 1
fi

rm -rf $BUILDDIR
